In [1]:
#머신러닝,딥러닝 NaN Null 값 처리, 문자열은 허용이 안되서 수치 값으로 변환

In [2]:
# 레이블 인코딩 , 원-핫 인코딩

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
items= ['TV','냉장고','전자레인지','컴퓨터','선풍기']

In [5]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

In [6]:
labels

array([0, 1, 3, 4, 2], dtype=int64)

In [7]:
encoder.classes_

array(['TV', '냉장고', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [14]:
encoder.inverse_transform([0,1,4,2,3])

array(['TV', '냉장고', '컴퓨터', '선풍기', '전자레인지'], dtype='<U5')

In [17]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
items = ['TV','냉장고','컴퓨터','선풍기','전자레인지']

In [18]:
encoder = LabelEncoder()

In [19]:
encoder.fit(items)

LabelEncoder()

In [20]:
labels = encoder.transform(items)

In [21]:
labels

array([0, 1, 4, 2, 3], dtype=int64)

In [22]:
labels.shape

(5,)

In [23]:
labels = labels.reshape(-1,1)

In [24]:
labels.shape

(5, 1)

In [25]:
oh_encoder = OneHotEncoder() #데이터 건수 만큼의 행이 필요
oh_encoder.fit(labels)

OneHotEncoder()

In [26]:
oh_labels = oh_encoder.transform(labels)

In [27]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])